# Generated by Django 4.1.5 on 2023-01-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fscohort", "0002_alter_student_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["number"], "verbose_name_plural": "Student_list"},
        ),
    ]
